### ISSUE TITLE
hi,how to run your test

### ISSUE THREAD

**Issue by qiangzhang007** [TianLanhe/TCP_Nat_Traversal#1]
hi,how to run your test

**Comment by TianLanhe** [comment]
emmm，first of all,you should have a server which has two unique global ip to privide the function of checking the nat type.do you have such a server?

**Comment by qiangzhang007** [comment]
sure，why must two golbal ip for a server?  what next  step?
方便加一下QQ 或者 微信吗

**Comment by TianLanhe** [comment]
sure，既然会中文为什么要说英语呢，哈哈哈，qq：849416763

**Comment by qiangzhang007** [comment]
u are prety nice guy!

**Comment by qiangzhang007** [comment]
add your qq,  need answer for  "我的真实姓名"

**Comment by TianLanhe** [comment]
你QQ多少，我加你吧

**Comment by qiangzhang007** [comment]
281927857
